name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: peremartra
          template: classic
          
          # ESTO ES LO IMPORTANTE:
          base: repositories           # Solo activa la sección de repositorios
          base_sections: repositories # Fuerza a que solo se vea esa parte
          base_subcore: repositories   # Muestra solo el contador de estrellas y forks
          
          # Desactivamos todo lo demás explícitamente por si acaso
          plugin_languages: no
          plugin_lines: no
          config_timezone: Europe/Madrid
